# Form implementation generated from reading ui file 'ui/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.playnote1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playnote1.setGeometry(QtCore.QRect(170, 220, 71, 41))
        self.playnote1.setObjectName("playnote1")
        self.playnotes = QtWidgets.QButtonGroup(MainWindow)
        self.playnotes.setObjectName("playnotes")
        self.playnotes.addButton(self.playnote1)
        self.playnote2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playnote2.setGeometry(QtCore.QRect(250, 220, 71, 41))
        self.playnote2.setObjectName("playnote2")
        self.playnotes.addButton(self.playnote2)
        self.playnote3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playnote3.setGeometry(QtCore.QRect(330, 220, 71, 41))
        self.playnote3.setObjectName("playnote3")
        self.playnotes.addButton(self.playnote3)
        self.playnote4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playnote4.setGeometry(QtCore.QRect(410, 220, 71, 41))
        self.playnote4.setObjectName("playnote4")
        self.playnotes.addButton(self.playnote4)
        self.playnote5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playnote5.setGeometry(QtCore.QRect(500, 220, 71, 41))
        self.playnote5.setObjectName("playnote5")
        self.playnotes.addButton(self.playnote5)
        self.playmelody = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playmelody.setGeometry(QtCore.QRect(310, 430, 141, 41))
        self.playmelody.setObjectName("playmelody")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 350, 161, 41))
        self.label.setStyleSheet("font-size:20px;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playnote1.setText(_translate("MainWindow", "q"))
        self.playnote2.setText(_translate("MainWindow", "w"))
        self.playnote3.setText(_translate("MainWindow", "e"))
        self.playnote4.setText(_translate("MainWindow", "r"))
        self.playnote5.setText(_translate("MainWindow", "t"))
        self.playmelody.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Пример мелодии"))
